name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  kakao_flutter_sdk_common: ^1.9.7+3
  kakao_flutter_sdk_user: ^1.4.3
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.2
  kakao_flutter_sdk: ^1.9.7+3
  url_launcher: ^6.1.7
  uni_links: ^0.5.1
  http: ^0.13.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_icon.png
